// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK8yW-JLZwu9UEAk3naILbznLqVEkNUdQ',
    appId: '1:160463073996:web:bd6dadde76075ee963c869',
    messagingSenderId: '160463073996',
    projectId: 'aquafatec-2b1bb',
    authDomain: 'aquafatec-2b1bb.firebaseapp.com',
    databaseURL: 'https://aquafatec-2b1bb-default-rtdb.firebaseio.com',
    storageBucket: 'aquafatec-2b1bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr51swT4zscpSiWZ94Y6ELwfl_SiPoG3o',
    appId: '1:160463073996:android:9bbcfb94db24760b63c869',
    messagingSenderId: '160463073996',
    projectId: 'aquafatec-2b1bb',
    databaseURL: 'https://aquafatec-2b1bb-default-rtdb.firebaseio.com',
    storageBucket: 'aquafatec-2b1bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgtehaWMijZ6jj6QqJRk0ZKpAqMQW_080',
    appId: '1:160463073996:ios:f6b83d450823cd6b63c869',
    messagingSenderId: '160463073996',
    projectId: 'aquafatec-2b1bb',
    databaseURL: 'https://aquafatec-2b1bb-default-rtdb.firebaseio.com',
    storageBucket: 'aquafatec-2b1bb.appspot.com',
    iosBundleId: 'com.example.aquafatec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQB1mUjXJ5rcU6THQo-564pOvWfiYu9fA',
    appId: '1:13271250399:ios:28733cd50bc70825ae806a',
    messagingSenderId: '13271250399',
    projectId: 'aquafatec-5daef',
    storageBucket: 'aquafatec-5daef.appspot.com',
    iosClientId: '13271250399-jfujo7bfggiivttn8cr4a19e74b89u36.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquafatec.RunnerTests',
  );
}