// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_a4Im5D-qFY8zEsYwFpl3MpBE2uy9x3M',
    appId: '1:13271250399:web:6bea7379ea3f17a6ae806a',
    messagingSenderId: '13271250399',
    projectId: 'aquafatec-5daef',
    authDomain: 'aquafatec-5daef.firebaseapp.com',
    storageBucket: 'aquafatec-5daef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZIVvCRRqtbeucS_5s7cyG0hAF5xeklAc',
    appId: '1:13271250399:android:684390353b1ddbe9ae806a',
    messagingSenderId: '13271250399',
    projectId: 'aquafatec-5daef',
    storageBucket: 'aquafatec-5daef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQB1mUjXJ5rcU6THQo-564pOvWfiYu9fA',
    appId: '1:13271250399:ios:1442353a46ecb708ae806a',
    messagingSenderId: '13271250399',
    projectId: 'aquafatec-5daef',
    storageBucket: 'aquafatec-5daef.appspot.com',
    iosClientId: '13271250399-htgg3rdtcj3l23njdot2kvmll1jln323.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquafatec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQB1mUjXJ5rcU6THQo-564pOvWfiYu9fA',
    appId: '1:13271250399:ios:28733cd50bc70825ae806a',
    messagingSenderId: '13271250399',
    projectId: 'aquafatec-5daef',
    storageBucket: 'aquafatec-5daef.appspot.com',
    iosClientId: '13271250399-jfujo7bfggiivttn8cr4a19e74b89u36.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquafatec.RunnerTests',
  );
}
